In [3]:
import numpy as np
from numpy.linalg import norm

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Умножим на 2 йю строк и вычтем её из второй

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

вычтем из 3 1
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Значит -2x3+3x4=4, система имеет множество решений.
x4=c
x3=-(4-3c)/2
x2=2-(4-3c)/2-3c
x1=-(2-(4-3c)/2-3c)-(4-3c)/2+2c

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

Найдём определители

In [12]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
a1 = np.array([[4, -1, 1], [-17, -5, -3], [0, 1, -1]])
a2 = np.array([[3, 4, 1], [2, -17, -3], [1, 0, -1]])
a3 = np.array([[3, -1, 4], [2, -5, -17], [1, 1, 0]])
det_a=np.linalg.det(a)
det_a1=np.linalg.det(a1)
det_a2=np.linalg.det(a2)
det_a3=np.linalg.det(a3)
print('определители',det_a,det_a1,det_a2,det_a3)
x1=det_a1/det_a
x2=det_a2/det_a
x3=det_a3/det_a
print('решение',x1,x2,x3)

определители 32.0 32.0 64.00000000000003 95.99999999999999
решение 1.0 2.000000000000001 2.9999999999999996


значит система совместна и имеет одно решение. вектор (1,2,3)

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

методом гаусса видно, что если из 1 уравнения вычесть 2 уравнение умноженное на 2, то получим 0=1 , а значит система решений не имеет и не совместна

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

методом гаусса обнулить 1 или 2 строку не получится, т.к. коэффициенты непропорциональны, также очевидно что уравнений меньше чем переменных, а занчит система имеет множество решений и совместна

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

коэффициенты непроворциональны, количество уравнений и переменных равно. система совместна и имеет одно решение
x4=1/2, x3=4/3, x2=(2-1/2)/5, x1=3-(2-1/2)/5+4/3-1/2

In [14]:
x4=1/2
x3=4/3, 
x2=(2-1/2)/5 
x1=3-(2-1/2)/5+4/3-1/2
print(x1,x2,x3,x4)

3.533333333333333 0.3 (1.3333333333333333,) 0.5


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

попробуем привести к ступенчатой форме и получим
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a-2c
\end{matrix}
\end{pmatrix}.$$

если c-3a-2x!=0 то система является несовместной

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [15]:
a = np.array([[1, -2], [3, -4]])
a1 = np.array([[1, -2], [7, -4]])
a2 = np.array([[1, 1], [3, 7]])
det_a=np.linalg.det(a)
det_a1=np.linalg.det(a1)
det_a2=np.linalg.det(a2)
print('определители',det_a,det_a1,det_a2)
x1=det_a1/det_a
x2=det_a2/det_a
print('решение',x1,x2)

определители 2.0000000000000004 9.999999999999998 4.0
решение 4.999999999999998 1.9999999999999996


Ответ: x1=5, x2=2

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [16]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
det_a=np.linalg.det(a)
det_a1=np.linalg.det(a1)
det_a2=np.linalg.det(a2)
det_a3=np.linalg.det(a3)
print('определители',det_a,det_a1,det_a2,det_a3)
x1=det_a1/det_a
x2=det_a2/det_a
x3=det_a3/det_a
print('решение',x1,x2,x3)

определители 42.99999999999998 86.00000000000004 -43.000000000000014 42.99999999999998
решение 2.0000000000000018 -1.0000000000000009 1.0


Ответ x1=2, x2=-1, x3=1 (2,-1,1)

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

l21=2, l31=3
$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

l32=4

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

l21=2, l31=3, l41=4
$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

l32=5, l42=6
$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

l43=7
$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{matrix}\right|
\begin{matrix}
1\\ 
-6\\
-5
\end{matrix}
\end{pmatrix}.$$

$$l_{21}=11/2, l_{31}=9/2$$

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 7/2 & -19/2
\end{pmatrix}$$

$$b=\begin{pmatrix}
1  \\ 
-23/2 \\ 
-19/2 
\end{pmatrix}$$

$$l_{32}=7/3$$

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & 52/3
\end{pmatrix}$$

$$b=\begin{pmatrix}
1  \\ 
-23/2 \\ 
52/3 
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & 7/3 & 1
\end{pmatrix}$$

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
11/2y_{1}+y_{2}=-6, \\
9/2y_{1}+7/3y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-23/2,$$
$$y_{3}=52/3$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
3/2x_{2}-23/2x_{3}=-23/2, \\
52/3x_{3}=52/3.
\end{cases}$$

$$x_{3}=1,$$
$$x_{2}=0,$$
$$x_{1}=-1.$$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{\sqrt{81}}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{\sqrt{81}}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 -{(-5)}^{2}}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{-15-5\cdot(-5)}{5}=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-5^2-2^2}=3.$$


Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-33,$$

$$y_{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=-5,$$

$$x_{1}=6.$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [25]:
def decompose_to_LU(a):
    """Decompose matrix of coefficients to L and U matrices.
     L and U triangular matrices will be represented in a single nxn matrix.
    :param a: numpy matrix of coefficients
    :return: numpy LU matrix
    """
    # create emtpy LU-matrix
    lu_matrix = np.matrix(np.zeros([a.shape[0], a.shape[1]]))
    n = a.shape[0]

    for k in range(n):
        # calculate all residual k-row elements
        for j in range(k, n):
            lu_matrix[k, j] = a[k, j] - lu_matrix[k, :k] * lu_matrix[:k, j]
        # calculate all residual k-column elemetns
        for i in range(k + 1, n):
            lu_matrix[i, k] = (a[i, k] - lu_matrix[i, : k] * lu_matrix[: k, k]) / lu_matrix[k, k]

    return lu_matrix


def get_L(m):
    """Get triangular L matrix from a single LU-matrix
    :param m: numpy LU-matrix
    :return: numpy triangular L matrix
    """
    L = m.copy()
    for i in range(L.shape[0]):
            L[i, i] = 1
            L[i, i+1 :] = 0
    return np.matrix(L)


def get_U(m):
    """Get triangular U matrix from a single LU-matrix
    :param m: numpy LU-matrix
    :return: numpy triangular U matrix
    """
    U = m.copy()
    for i in range(1, U.shape[0]):
        U[i, :i] = 0
    return U

def solve_LU(lu_matrix, b):
    """Solve system of equations from given LU-matrix and vector b of absolute terms.
    :param lu_matrix: numpy LU-matrix
    :param b: numpy matrix of absolute terms [n x 1]
    :return: numpy matrix of answers [n x 1]
    """
    # get supporting vector y
    y = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(y.shape[0]):
        y[i, 0] = b[i, 0] - lu_matrix[i, :i] * y[:i]

    # get vector of answers x
    x = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(1, x.shape[0] + 1):
        x[-i, 0] = (y[-i] - lu_matrix[-i, -i:] * x[-i:, 0] )/ lu_matrix[-i, -i]

    return x

In [40]:
a=np.matrix('2 1 3; 11 7 5; 9 8 4')
print(a)

b=np.matrix('1; -6; -5')
print(b)

LU = decompose_to_LU(a)
L = get_L(LU)
U = get_U(LU)
print('L-matrix', L)
print('U-matrix', U)
x=solve_LU(decompose_to_LU(a),b)
print('Ответ',x)

[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]
[[ 1]
 [-6]
 [-5]]
L-matrix [[1.         0.         0.        ]
 [5.5        1.         0.        ]
 [4.5        2.33333333 1.        ]]
U-matrix [[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]
Ответ [[-1.]
 [ 0.]
 [ 1.]]
